### PR TITLE
Fixed bug: ProgramRuntimeFake does not implement fw.ProgramRuntime

### PR DESCRIPTION
**Pull request by alldroll**
This fixes the bug:
```
# github.com/short-d/app/mdtest [github.com/short-d/app/mdtest.test]
mdtest/runtime.go:9:5: cannot use (*ProgramRuntimeFake)(nil) (type *ProgramRuntimeFake) as type fw.ProgramRuntime in assignment:
	*ProgramRuntimeFake does not implement fw.ProgramRuntime (missing LockOSThread method)
# github.com/short-d/app/mdtest
mdtest/runtime.go:9:5: cannot use (*ProgramRuntimeFake)(nil) (type *ProgramRuntimeFake) as type fw.ProgramRuntime in assignment:
	*ProgramRuntimeFake does not implement fw.ProgramRuntime (missing LockOSThread method)
``` 

The regression has caused by https://github.com/short-d/app/pull/61 and it is definitely due to lack of CI/CD (testing)

### CODE REVIEW

**Comment by byliuyang** [comment]
https://github.com/short-d/app/pull/62

**Comment by byliuyang** [comment]
https://github.com/short-d/app/issues/64
